"""empty message

Revision ID: 6dd7eafe15ad
Revises: 
Create Date: 2018-09-01 11:37:59.559000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd7eafe15ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=20), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=20000000000000L), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('total_read', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment__system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blogname', sa.String(length=50), nullable=True),
    sa.Column('slogan', sa.String(length=500), nullable=True),
    sa.Column('myurl', sa.String(length=2000), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('about_blog', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=222), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('settings')
    op.drop_table('comment__system')
    op.drop_table('coin')
    op.drop_table('blogpost')
    # ### end Alembic commands ###
